Repository runners-sh/website, pull requests merged in 2025-06, with the labels that each got.

#57 feat!: make solstice auto detect the caller
  .gitignore
  main-site/__main__.py
  main-site/e2e/conftest.py
  runners_common/__init__.py
  runners_common/__main__.py
  runners_common/funbar.py
  solstice/cli.py
  solstice/sitegen.py
Labels: breaking

#64 content(main-site): Simple data pipelining in C++
  main-site/blog/cxx_template_pipelines.md
  main-site/public/img/cxx_pipelines/gopy.jpg
Labels: content

#68 feat: snazzy multicolored barcode
  main-site/e2e/test_screenshots.py
  main-site/public/css/barcode.css
  main-site/public/css/blog.css
  main-site/templates/blog.jinja
  runners_common/funbar.py
Labels: feat

#69 feat: better file reloading
  main-site/__main__.py
  solstice/cli.py
  solstice/sitegen.py
Labels: feat

#67 feat: member pages
  main-site/__main__.py
  main-site/blog/cat_states.md
  main-site/blog/cxx_template_pipelines.md
  main-site/blog/gallery.md
  main-site/blog/languages.md
  main-site/blog/shellcode-encryption.md
  main-site/e2e/conftest.py
  main-site/e2e/test_gallery.py
  main-site/e2e/test_member.py
  main-site/e2e/test_screenshots.py
  main-site/member/jayvesmir.md
  main-site/member/peppidesu.md
  main-site/member/vym.md
  main-site/public/css/blog-overview.css
  main-site/public/css/common.css
  main-site/public/css/member.css
  main-site/public/img/discord-brands-solid.svg
  main-site/public/img/github-alt-brands-solid.svg
  main-site/public/pfp/peppidesu.avif
  main-site/templates/blog-overview.jinja
  main-site/templates/blog.jinja
  main-site/templates/comps.jinja
  main-site/templates/icon/bsky.svg
  main-site/templates/icon/discord.svg
  main-site/templates/icon/github.svg
  main-site/templates/icon/globe.svg
  main-site/templates/icon/mastodon.svg
  main-site/templates/member.jinja
Labels: feat

#75 content: added profile info for jayvesmir
  main-site/member/jayvesmir.md
  main-site/public/pfp/jayvesmir.avif
Labels: content

#72 refactor!: deprecate `with` syntax for `Page` and `MarkdownPage`
  main-site/__main__.py
  solstice/__init__.py
  solstice/sitegen.py
Labels: breaking

#71 feat: nicer inline code
  main-site/public/css/blog-overview.css
  main-site/public/css/common.css
Labels: feat

#77 fix: remove fenced code block text background
  main-site/public/css/common.css
Labels: fix
